database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "root"
    database: "discord"
  redis:
    host: "localhost"
    port: 6379
    auth: ""
    channel: "discordsync"